spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 对应自己的数据库连接
    url: jdbc:mysql://xxx:3306/kk?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
    username: xxx
    password: xxx
    # Druid连接池的配置信息 Begin ##################################################
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接大小
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      # 获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      # 归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
      # 开启poolPreparedStatements后生效
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      log-slow-sql: true

    # Druid连接池的配置信息 End ######################################################
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

